# This file was generated by the {rix} R package v0.18.2 on 2026-05-31
# with following call:
# >rix(date = latest_date,
#  > r_pkgs = c("devtools",
#  > "testthat",
#  > "pkgdown",
#  > "shinytest2",
#  > "formattable",
#  > "stringr",
#  > "shinyvalidate",
#  > "Seurat",
#  > "SeuratObject",
#  > "ape",
#  > "biomaRt",
#  > "colourpicker",
#  > "dplyr",
#  > "DT",
#  > "future.apply",
#  > "ggplot2",
#  > "glue",
#  > "GSVA",
#  > "HDF5Array",
#  > "httr",
#  > "igraph",
#  > "Matrix",
#  > "msigdbr",
#  > "pbapply",
#  > "plotly",
#  > "qvalue",
#  > "R6",
#  > "readr",
#  > "rlang",
#  > "scales",
#  > "shiny",
#  > "shinycssloaders",
#  > "shinydashboard",
#  > "shinyFiles",
#  > "shinyjs",
#  > "shinyWidgets",
#  > "tibble",
#  > "tidyr",
#  > "tidyselect",
#  > "viridis"),
#  > system_pkgs = c("chromium",
#  >      "pandoc"),
#  > git_pkgs = list(list(package_name = "BPCells",
#  > repo_url = "https://github.com/bnprks/BPCells/r",
#  > commit = bpcells_sha)),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.6.0")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-05-25.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      ape
      biomaRt
      colourpicker
      devtools
      dplyr
      DT
      formattable
      future_apply
      ggplot2
      glue
      GSVA
      HDF5Array
      httr
      igraph
      Matrix
      msigdbr
      pbapply
      pkgdown
      plotly
      qvalue
      R6
      readr
      rlang
      scales
      Seurat
      SeuratObject
      shiny
      shinycssloaders
      shinydashboard
      shinyFiles
      shinyjs
      shinytest2
      shinyvalidate
      shinyWidgets
      stringr
      testthat
      tibble
      tidyr
      tidyselect
      viridis;
  };
 
    BPCells-src = pkgs.fetchgit {
      url = "https://github.com/bnprks/BPCells";
      rev = "adc4a3c30f60a03522f58947d733d7d77a6eb2cf";
      sha256 = "sha256-7VRa1iADZ3Btcke8IHqCF97O2HhE184dZ1cH1i66Uhc=";
    };

    BPCells = (pkgs.rPackages.buildRPackage {
      name = "BPCells";
      src = "${BPCells-src}/r";
      postPatch = "patchShebangs configure";
      nativeBuildInputs = [ pkgs.hdf5.dev ];
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          magrittr
          Matrix
          Rcpp
          rlang
          vctrs
          lifecycle
          stringr
          tibble
          dplyr
          tidyr
          readr
          ggplot2
          scales
          patchwork
          scattermore
          ggrepel
          RColorBrewer
          hexbin
          RcppEigen;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      chromium
      glibcLocales
      nix
      pandoc
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ BPCells rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
