# This file was generated by the {rix} R package v0.16.0 on 2026-05-09
# with following call:
# >rix(r_ver = "e4d84e0e4293e6ca35481a57530ea9680e7d93d1",
#  > r_pkgs = c("devtools",
#  > "testthat",
#  > "shinytest2",
#  > "shinyvalidate",
#  > "Seurat",
#  > "ape",
#  > "biomaRt",
#  > "colourpicker",
#  > "dplyr",
#  > "DT",
#  > "future.apply",
#  > "ggplot2",
#  > "glue",
#  > "GSVA",
#  > "HDF5Array",
#  > "httr",
#  > "igraph",
#  > "Matrix",
#  > "msigdbr",
#  > "pbapply",
#  > "plotly",
#  > "qvalue",
#  > "R6",
#  > "readr",
#  > "rlang",
#  > "scales",
#  > "shiny",
#  > "shinycssloaders",
#  > "shinydashboard",
#  > "shinyFiles",
#  > "shinyjs",
#  > "shinyWidgets",
#  > "tibble",
#  > "tidyr",
#  > "tidyselect",
#  > "viridis"),
#  > system_pkgs = c("chromium"),
#  >      git_pkgs = list(list(package_name = "BPCells",
#  > repo_url = "https://github.com/bnprks/BPCells/r",
#  > commit = "16faeade0a26b392637217b0caf5d7017c5bdf9b")),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses upstream nixpkgs' revision e4d84e0e4293e6ca35481a57530ea9680e7d93d1 for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/e4d84e0e4293e6ca35481a57530ea9680e7d93d1.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      ape
      biomaRt
      colourpicker
      devtools
      dplyr
      DT
      future_apply
      ggplot2
      glue
      GSVA
      HDF5Array
      httr
      igraph
      Matrix
      msigdbr
      pbapply
      plotly
      qvalue
      R6
      readr
      rlang
      scales
      Seurat
      shiny
      shinycssloaders
      shinydashboard
      shinyFiles
      shinyjs
      shinytest2
      shinyvalidate
      shinyWidgets
      testthat
      tibble
      tidyr
      tidyselect
      viridis;
  };
 
    BPCells-src = pkgs.fetchgit {
      url = "https://github.com/bnprks/BPCells";
      rev = "16faeade0a26b392637217b0caf5d7017c5bdf9b";
      sha256 = "sha256-8un4tazyJ3asjC4J/9AAAmRI584JPEjE3iL1i7BB8jk=";
    };

    BPCells = (pkgs.rPackages.buildRPackage {
      name = "BPCells";
      src = "${BPCells-src}/r";
      postPatch = "patchShebangs configure";
      nativeBuildInputs = [ pkgs.hdf5.dev ];
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          magrittr
          Matrix
          Rcpp
          rlang
          vctrs
          lifecycle
          stringr
          tibble
          dplyr
          tidyr
          readr
          ggplot2
          scales
          patchwork
          scattermore
          ggrepel
          RColorBrewer
          hexbin
          RcppEigen;
      };
    });
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      chromium
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ BPCells rpkgs   system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
