name: R-CMD-check

on:
  pull_request:
    branches: [master]
  # for manual trigger
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Testing cache'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v6

      - name: Create this folder to silence warning
        run: mkdir -p ~/.nix-defexpr/channels

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      
      # enable binary caches for faster installs: rstats-on-nix for many R packages
      - uses: cachix/cachix-action@v17
        with:
          name: rstats-on-nix

      # enable mihem cache for BPCells and any other packages not in rstats-on-nix
      - uses: cachix/cachix-action@v17
        with:
          name: mihem
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # Install R package dependencies via nix-shell, using the default.nix file in the repository
      - name: Install R package dependencies
        run: nix-shell default.nix --run "echo 'R package dependencies installed'"

      # Run R CMD check via devtools::check()
      - name: Run R-CMD-check
        run: |
          nix-shell default.nix --run "Rscript -e \"
            devtools::check(vignettes = TRUE, error_on = 'error')
          \""

      - name: Upload check results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: r-cmd-check-results
          path: "*.Rcheck/"
          retention-days: 14
